# Generated by Django 6.0.3 on 2026-03-18 08:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TreatmentExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('exercise_id', models.PositiveIntegerField()),
                ('exercise_name', models.CharField(max_length=200)),
                ('assigned_level', models.PositiveIntegerField(default=1)),
                ('current_level', models.PositiveIntegerField(default=1)),
                ('notes', models.TextField(blank=True)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['assigned_at'],
            },
        ),
        migrations.CreateModel(
            name='LevelProgression',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_level', models.PositiveIntegerField()),
                ('to_level', models.PositiveIntegerField()),
                ('progressed_at', models.DateTimeField(auto_now_add=True)),
                ('reason', models.TextField(blank=True)),
                ('treatment_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='progressions', to='treatments.treatmentexercise')),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eva_before', models.PositiveIntegerField(blank=True, null=True, verbose_name='EVA antes del ejercicio')),
                ('eva_after', models.PositiveIntegerField(blank=True, null=True, verbose_name='EVA después del ejercicio')),
                ('is_completed', models.BooleanField(default=False)),
                ('completion_notes', models.TextField(blank=True)),
                ('session_date', models.DateTimeField(auto_now_add=True)),
                ('treatment_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='treatments.treatmentexercise')),
            ],
        ),
        migrations.CreateModel(
            name='TreatmentPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='treatment_plans', to=settings.AUTH_USER_MODEL)),
                ('physiotherapist', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_plans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='treatmentexercise',
            name='treatment_plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='treatments.treatmentplan'),
        ),
    ]
