# Generated by Django 6.0.3 on 2026-03-18 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('treatments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='treatmentplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='treatmentplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
