# Generated by Django 6.0.3 on 2026-03-18 08:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BodySegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100, verbose_name='Nombre en español')),
                ('atlas_image', models.ImageField(blank=True, null=True, upload_to='atlas/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Body Segment',
                'verbose_name_plural': 'Body Segments',
            },
        ),
        migrations.CreateModel(
            name='ExerciseCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('name_es', models.CharField(max_length=50, verbose_name='Nombre en español')),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Exercise Category',
                'verbose_name_plural': 'Exercise Categories',
            },
        ),
        migrations.CreateModel(
            name='BodySubSegment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100, verbose_name='Nombre en español')),
                ('atlas_image', models.ImageField(blank=True, null=True, upload_to='atlas/')),
                ('description', models.TextField(blank=True)),
                ('segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_segments', to='exercises.bodysegment')),
            ],
            options={
                'verbose_name': 'Body Sub-Segment',
                'verbose_name_plural': 'Body Sub-Segments',
            },
        ),
        migrations.CreateModel(
            name='Muscle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100, verbose_name='Nombre en español')),
                ('sub_segments', models.ManyToManyField(related_name='muscles', to='exercises.bodysubsegment')),
            ],
            options={
                'verbose_name': 'Muscle',
                'verbose_name_plural': 'Muscles',
            },
        ),
        migrations.CreateModel(
            name='Pathology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('name_es', models.CharField(max_length=100, verbose_name='Nombre en español')),
                ('description', models.TextField(blank=True)),
                ('affected_segments', models.ManyToManyField(related_name='pathologies', to='exercises.bodysegment')),
            ],
            options={
                'verbose_name': 'Pathology',
                'verbose_name_plural': 'Pathologies',
            },
        ),
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.PositiveIntegerField(choices=[(1, 'Nivel 1'), (2, 'Nivel 2'), (3, 'Nivel 3'), (4, 'Nivel 4'), (5, 'Nivel 5')], default=1)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('instructions', models.TextField()),
                ('reference_image', models.ImageField(blank=True, null=True, upload_to='exercises/')),
                ('muscle_image', models.ImageField(blank=True, null=True, upload_to='exercises/muscles/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sub_segment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.bodysubsegment')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exercises', to='exercises.exercisecategory')),
                ('muscles', models.ManyToManyField(blank=True, related_name='exercises', to='exercises.muscle')),
                ('pathologies', models.ManyToManyField(blank=True, related_name='exercises', to='exercises.pathology')),
            ],
            options={
                'ordering': ['level', 'category', 'name'],
            },
        ),
    ]
